import React from 'react';

interface AIContextBannerProps {
  teacherName: string;
  subject: string;
  grade: string;
}

export function AIContextBanner({ teacherName, subject, grade }: AIContextBannerProps) {
  return (
    <div className="bg-neutral-900 rounded-2xl p-5 mb-5 text-white shadow-md animate-in fade-in slide-in-from-top-3 duration-300">
      <p className="text-xs font-semibold text-neutral-300 leading-relaxed max-w-xl">
        Certainly, John! Here is your customized Question Paper generated by VedaAI for your CBSE Grade {grade} {subject} classes:
      </p>
      <div className="flex items-center gap-2 mt-3.5">
        <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
        <span className="bg-amber-400 text-neutral-950 text-[10px] font-extrabold uppercase px-2.5 py-0.5 rounded-md tracking-wider shadow-xs">
          {teacherName}
        </span>
      </div>
    </div>
  );
}
